service: serverless-101-tlakomy

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  bye:
    handler: byehandler.bye
    events:
      - http:
          path: /
          method: get
