service: workshop-${self:custom.name}

custom:
  name: tomasz
  email: tlakomy90@gmail.com

provider:
  name: aws
  runtime: nodejs12.x

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
